Built from wonderful book - https://github.com/jakevdp/PythonDataScienceHandbook

In [2]:
import numpy as np

In [2]:
np.array([1,2,4,6])

array([1, 2, 4, 6])

In [4]:
np.array([1,2,4,6], dtype = 'float32')

array([1., 2., 4., 6.], dtype=float32)

In [5]:
np.array([1.3, 2.5 ,4,6], dtype = int)

array([1, 2, 4, 6])

In [6]:
np.array([1.3, 2.5 ,4,6], dtype = float)

array([1.3, 2.5, 4. , 6. ])

In [11]:
## uniformly distributed random values between 0 & 1
np.random.random((3,2))

array([[0.67331537, 0.58414402],
       [0.11715069, 0.06728735],
       [0.89133443, 0.53696526]])

In [13]:
## gaussian distribution: random values with mean=0 and std=1
np.random.randn(3,2)

array([[-0.37081951,  0.35305599],
       [-0.24237967, -1.1929943 ],
       [-1.69440667,  0.71284138]])

In [14]:
## gaussian distribution: random values with mean=0 and std=1
np.random.normal(loc = 0, scale = 1, size = (3,2))

array([[-2.38289193,  0.24988464],
       [-0.46452397,  0.49530669],
       [ 1.30490215, -0.92265913]])

In [16]:
np.random.randint(low = 0, high = 4, size = (3,2))

array([[3, 1],
       [0, 1],
       [3, 2]])

In [19]:
x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array
x1, x2, x3

(array([8, 3, 1, 8, 5, 7]),
 array([[2, 9, 6, 8],
        [7, 5, 0, 2],
        [7, 8, 2, 8]]),
 array([[[4, 8, 6, 1, 6],
         [3, 4, 2, 7, 2],
         [0, 8, 2, 3, 2],
         [1, 0, 7, 3, 2]],
 
        [[7, 4, 7, 9, 5],
         [0, 0, 6, 6, 6],
         [4, 5, 4, 8, 3],
         [4, 5, 6, 7, 0]],
 
        [[7, 1, 3, 3, 7],
         [5, 3, 2, 9, 2],
         [0, 4, 6, 5, 5],
         [2, 9, 8, 9, 2]]]))

In [24]:
print("x1 ndim: ", x1.ndim)
print("x1 shape:", x1.shape)
print("x1 size: ", x1.size)
print("itemsize:", x1.itemsize, "bytes")
print("nbytes:", x1.nbytes, "bytes")
print()
print("x2 ndim: ", x2.ndim)
print("x2 shape:", x2.shape)
print("x2 size: ", x2.size)
print("itemsize:", x2.itemsize, "bytes")
print("nbytes:", x2.nbytes, "bytes")
print()
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

x1 ndim:  1
x1 shape: (6,)
x1 size:  6
itemsize: 4 bytes
nbytes: 24 bytes

x2 ndim:  2
x2 shape: (3, 4)
x2 size:  12
itemsize: 4 bytes
nbytes: 48 bytes

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
itemsize: 4 bytes
nbytes: 240 bytes


Array slicing `x[start:stop:step]`

defaults- 
- start = 0
- stop = size of dimension
- step = 1

In [33]:
# 1D- array
x = np.arange(20)
print(x)
print(x[::2])
print(x[1::2])
print(x[::-1]) # reverese

# 2D- array
x = np.random.randint(20, size=(3,4))
print()
print(x)
print()
print(x[::2])
print()
print(x[1::2])
print()
print(x[::-1]) # not reverse for >=2D
print()
print(x[:3, ::2]) #  all rows, every other column
print()
print(x[::-1, ::-1]) # reverse

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  2  4  6  8 10 12 14 16 18]
[ 1  3  5  7  9 11 13 15 17 19]
[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]

[[ 1  6  5  8]
 [13 12  7  4]
 [ 6  3  8  7]]

[[1 6 5 8]
 [6 3 8 7]]

[[13 12  7  4]]

[[ 6  3  8  7]
 [13 12  7  4]
 [ 1  6  5  8]]

[[ 1  5]
 [13  7]
 [ 6  8]]

[[ 7  8  3  6]
 [ 4  7 12 13]
 [ 8  5  6  1]]


In [38]:
x = np.array([1,2,3])
print(x.shape)
print(x[:,None].shape)
print(x[None,:].shape)
print(x[:, np.newaxis].shape)
print(x[np.newaxis, :].shape)
print()
x = np.random.randn(2,3)
print(x.shape)
print(x[:,None].shape)
print(x[None,:].shape)
print(x[:,:, None].shape)
print(x[:, np.newaxis].shape)
print(x[np.newaxis, :].shape)
print(x[np.newaxis, :, :].shape)

(3,)
(3, 1)
(1, 3)
(3, 1)
(1, 3)

(2, 3)
(2, 1, 3)
(1, 2, 3)
(2, 3, 1)
(2, 1, 3)
(1, 2, 3)
(1, 2, 3)


In [40]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x)
print(x1, x2, x3)
print()

grid = np.arange(16).reshape((4, 4))
print(grid)
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)
left, right = np.hsplit(grid, [2])
print(left)
print(right)


[1, 2, 3, 99, 99, 3, 2, 1]
[1 2 3] [99 99] [3 2 1]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [52]:
np.log(1+100), np.log1p(1+100),'vs' , np.log(1+0.001), np.log1p(1+0.001)

(4.61512051684126,
 4.624972813284271,
 'vs',
 0.0009995003330834232,
 0.6936470556015963)

##### Broadcasting

1. Rule 1
2. Rule 2
3. Rule 3
- Read here - https://jakevdp.github.io/PythonDataScienceHandbook/02.05-computation-on-arrays-broadcasting.html

##### Boolean

`==`, `>`, `<`, `!=`, `>=`, `<=`

In [53]:
a = np.random.randint(0,10, (4,4))
a

array([[4, 5, 9, 1],
       [6, 6, 2, 9],
       [7, 3, 3, 0],
       [6, 3, 6, 5]])

In [54]:
a>4

array([[False,  True,  True, False],
       [ True,  True, False,  True],
       [ True, False, False, False],
       [ True, False,  True,  True]])

In [55]:
np.sum(a>4)

9

In [56]:
np.count_nonzero(a > 4)

9

In [58]:
np.any(a > 4)

True

In [59]:
np.all(a > 8)

False

In [60]:
np.all(a > -1)

True

In [3]:
inches = np.random.randint(0, 20, (4,4))
inches

array([[ 6,  2,  0,  1],
       [17, 13, 19,  5],
       [ 7, 12, 17, 12],
       [ 2,  7, 11,  8]])

In [7]:
rainy = inches > 10
inches[rainy]

array([17, 13, 19, 12, 17, 12, 11])

In [5]:
rainy = (inches > 10) & (inches < 15)
inches[rainy]

array([13, 12, 12, 11])

` or `, ` | `, ` and `, ` & ` - https://jakevdp.github.io/PythonDataScienceHandbook/02.06-boolean-arrays-and-masks.html

In [8]:
a = np.arange(100)
np.random.choice(a, 20, replace = False)

array([59, 67, 52, 53, 23, 20, 33, 94, 54, 28, 31, 29, 81,  5, 95, 83, 70,
       40, 15, 37])

binning values