In [2]:
import numpy as np

### 1. binning
- numpy - https://jakevdp.github.io/PythonDataScienceHandbook/02.07-fancy-indexing.html

In [3]:
np.random.seed(42)
x = np.random.randn(100)
x

array([ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986, -0.23415337,
       -0.23413696,  1.57921282,  0.76743473, -0.46947439,  0.54256004,
       -0.46341769, -0.46572975,  0.24196227, -1.91328024, -1.72491783,
       -0.56228753, -1.01283112,  0.31424733, -0.90802408, -1.4123037 ,
        1.46564877, -0.2257763 ,  0.0675282 , -1.42474819, -0.54438272,
        0.11092259, -1.15099358,  0.37569802, -0.60063869, -0.29169375,
       -0.60170661,  1.85227818, -0.01349722, -1.05771093,  0.82254491,
       -1.22084365,  0.2088636 , -1.95967012, -1.32818605,  0.19686124,
        0.73846658,  0.17136828, -0.11564828, -0.3011037 , -1.47852199,
       -0.71984421, -0.46063877,  1.05712223,  0.34361829, -1.76304016,
        0.32408397, -0.38508228, -0.676922  ,  0.61167629,  1.03099952,
        0.93128012, -0.83921752, -0.30921238,  0.33126343,  0.97554513,
       -0.47917424, -0.18565898, -1.10633497, -1.19620662,  0.81252582,
        1.35624003, -0.07201012,  1.0035329 ,  0.36163603, -0.64

In [4]:
bins = np.linspace(-5, 5, 20)
bins

array([-5.        , -4.47368421, -3.94736842, -3.42105263, -2.89473684,
       -2.36842105, -1.84210526, -1.31578947, -0.78947368, -0.26315789,
        0.26315789,  0.78947368,  1.31578947,  1.84210526,  2.36842105,
        2.89473684,  3.42105263,  3.94736842,  4.47368421,  5.        ])

In [10]:
counts = np.zeros_like(bins)
counts

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [11]:
i = np.searchsorted(bins, x)
i

array([11, 10, 11, 13, 10, 10, 13, 11,  9, 11,  9,  9, 10,  6,  7,  9,  8,
       11,  8,  7, 13, 10, 10,  7,  9, 10,  8, 11,  9,  9,  9, 14, 10,  8,
       12,  8, 10,  6,  7, 10, 11, 10, 10,  9,  7,  9,  9, 12, 11,  7, 11,
        9,  9, 11, 12, 12,  8,  9, 11, 12,  9, 10,  8,  8, 12, 13, 10, 12,
       11,  9, 11, 13, 10, 13,  5, 12, 10,  9, 10,  6, 10, 11, 13,  9,  8,
        9, 12, 11,  9, 11, 10, 12,  9,  9,  9,  7, 11, 10, 10, 10],
      dtype=int64)

In [12]:
np.add.at(counts, i, 1)
counts

array([ 0.,  0.,  0.,  0.,  0.,  1.,  3.,  7.,  9., 23., 22., 17., 10.,
        7.,  1.,  0.,  0.,  0.,  0.,  0.])

### 2. Sorting - insertion sorts, selection sorts, merge sorts, quick sorts, bubble sorts
- https://jakevdp.github.io/PythonDataScienceHandbook/02.08-sorting.html

In [15]:
## selection sort: given array sort in increasing order


def selection_sort_numpy(x):
    for i in range(len(x)):
        swap = i + np.argmin(x[i:])
        #print(swap)
        x[i], x[swap] = x[swap], x[i]
    return x


mylist1 = [0,2,5,3,1,6,4]
mylist2 = [2,5,3,1,6,4]

print(selection_sort_numpy(np.array(mylist1)))
print(selection_sort_numpy(np.array(mylist2)))

0
4
4
3
6
6
6
[0 1 2 3 4 5 6]
3
3
2
5
5
5
[1 2 3 4 5 6]


### 3. list comprehension
### 4. Dictionary

### 5. Pandas Assessment
- https://jakevdp.github.io/PythonDataScienceHandbook/03.07-merge-and-join.html
- join, merge, common df, intersection df, grouping, reset index, duplicates, nans, fillnans, dropna, dummies, scaling, datetime, time features, feature engg, mix type dtypes in columns, outliers, masking, condition across 1 or more columns

In [16]:
import pandas as pd

In [17]:
df = pd.DataFrame({'key': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'data': range(6)}, columns=['key', 'data'])
df

key  data
0   A     0
1   B     1
2   C     2
3   A     3
4   B     4
5   C     5

In [19]:
df.groupby('key').sum()

data
key      
A       3
B       5
C       7

In [21]:
df.groupby('key')['data'].mean()

key
A    1.5
B    2.5
C    3.5
Name: data, dtype: float64

In [23]:
for k, group in df.groupby('key'):
    print(k)
    print(group)

A
  key  data
0   A     0
3   A     3
B
  key  data
1   B     1
4   B     4
C
  key  data
2   C     2
5   C     5


In [26]:
df[df['data']>=2]

key  data
2   C     2
3   A     3
4   B     4
5   C     5

In [27]:
def sub2(x):
    return x-2

df['new_col'] = df['data'].apply(sub2)
df

key  data  new_col
0   A     0       -2
1   B     1       -1
2   C     2        0
3   A     3        1
4   B     4        2
5   C     5        3

In [32]:
import numpy as np
import pandas as pd
import seaborn as sns
titanic = sns.load_dataset('titanic')
titanic.head(2)

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False

In [30]:
titanic.groupby('sex')['survived'].mean()

sex
female    0.742038
male      0.188908
Name: survived, dtype: float64

In [31]:
titanic.groupby('sex')[['survived']].mean()

survived
sex             
female  0.742038
male    0.188908

In [38]:
titanic.groupby(['sex', 'class'])['survived'].mean().unstack()

C:\Users\mgupta70\AppData\Local\Temp\ipykernel_9096\3871282342.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  titanic.groupby(['sex', 'class'])['survived'].mean().unstack()


class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [42]:
# for k, group in titanic.groupby(['sex', 'class'])['survived']:
#     print(k)
#     print(k[0])
    #print(group)

## 6. convolve in numpy

## 7. plotting

## 8.
- df.apply
- lambda
- in
- not in
- is
- is in
- and vs &
- | vs or
- map

In [ ]:
# Source - https://jakevdp.github.io/PythonDataScienceHandbook/05.06-linear-regression.html

## adding binary columns to pandas df
days = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
for i in range(7):
    daily[days[i]] = (daily.index.dayofweek == i).astype(float)

## join advanced
from pandas.tseries.holiday import USFederalHolidayCalendar
cal = USFederalHolidayCalendar()
holidays = cal.holidays('2012', '2016')
daily = daily.join(pd.Series(1, index=holidays, name='holiday'))
daily['holiday'].fillna(0, inplace=True)

## feature engg
def hours_of_daylight(date, axis=23.44, latitude=47.61):
    """Compute the hours of daylight for the given date"""
    days = (date - pd.datetime(2000, 12, 21)).days
    m = (1. - np.tan(np.radians(latitude))
         * np.tan(np.radians(axis) * np.cos(days * 2 * np.pi / 365.25)))
    return 24. * np.degrees(np.arccos(1 - np.clip(m, 0, 2))) / 180.

daily['daylight_hrs'] = list(map(hours_of_daylight, daily.index))
daily[['daylight_hrs']].plot()
plt.ylim(8, 17)

## fancy
weather['dry day'] = (weather['PRCP'] == 0).astype(int)

daily = daily.join(weather[['PRCP', 'Temp (C)', 'dry day']])

# Finally, let's add a counter that increases from day 1, and measures how many years have passed. 
#This will let us measure any observed annual increase or decrease in daily crossings:

daily['annual'] = (daily.index - daily.index[0]).days / 365.


# Drop any rows with null values
daily.dropna(axis=0, how='any', inplace=True)

column_names = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun', 'holiday',
                'daylight_hrs', 'PRCP', 'dry day', 'Temp (C)', 'annual']
X = daily[column_names]
y = daily['Total']

model = LinearRegression(fit_intercept=False)
model.fit(X, y)
daily['predicted'] = model.predict(X)

daily[['Total', 'predicted']].plot(alpha=0.5);

In [14]:
a = input('who are you')

who are you 2


In [15]:
a

'2'

## List
1. insert
2. pop
3.  remove
4.  del
5. flatten
6. list comprehension


In [55]:
a = [1,2,4,5,6,7,8,9]

In [56]:
a.pop() # removes last

9

In [57]:
a

[1, 2, 4, 5, 6, 7, 8]

In [58]:
a.pop(0) # remove first

1

In [59]:
a

[2, 4, 5, 6, 7, 8]

In [60]:
a.remove(4) # removes value

In [61]:
a

[2, 5, 6, 7, 8]

In [62]:
a.insert(3 , 32) # at 4th place we insert 32

In [63]:
a

[2, 5, 6, 32, 7, 8]

In [64]:
len(a)

6

In [65]:
a.insert(5, 33) 

In [66]:
a

[2, 5, 6, 32, 7, 33, 8]

In [67]:
a.insert(7, 33) # for last idx = idx+1 # for last it is better to use append

In [69]:
del a[3]

In [70]:
a

[2, 5, 6, 7, 33, 8, 33]

In [31]:
a = [[1,2,4,5,6],[1,2,4,5,6]]

[e for nl in a for e in nl]

[1, 2, 4, 5, 6, 1, 2, 4, 5, 6]

In [79]:
[n for n in range(100) if (n%7==0) or (n%11==0) ]

[0,
 7,
 11,
 14,
 21,
 22,
 28,
 33,
 35,
 42,
 44,
 49,
 55,
 56,
 63,
 66,
 70,
 77,
 84,
 88,
 91,
 98,
 99]

In [112]:
# Each element is (name, semi-major axis (AU), eccentricity, orbit class)
Asteroids = [('Eros', 1.457916888347732, 0.2226769029627053, 'AMO'),
             ('Albert', 2.629584157344544, 0.551788195302116, 'AMO'),
             ('Alinda', 2.477642943521562, 0.5675993715753302, 'AMO'),
             ('Ganymed', 2.662242764279804, 0.5339300994578989, 'AMO'),
             ('Amor', 1.918987277620309, 0.4354863345648127, 'AMO'),
             ('Icarus', 1.077941311539208, 0.826950446001521, 'APO'),
             ('Betulia', 2.196489260519891, 0.4876246891992282, 'AMO'),
             ('Geographos', 1.245477192797457, 0.3355407124897842, 'APO'),
             ('Ivar', 1.862724540418448, 0.3968541470639658, 'AMO'),
             ('Toro', 1.367247622946547, 0.4358829575017499, 'APO'),
             ('Apollo', 1.470694262588244, 0.5598306817483757, 'APO'),
             ('Antinous', 2.258479598510079, 0.6070051516585434, 'APO'),
             ('Daedalus', 1.460912865705988, 0.6144629118218898, 'APO'),
             ('Cerberus', 1.079965807367047, 0.4668134997419173, 'APO'),
             ('Sisyphus', 1.893726635847921, 0.5383319204425762, 'APO'),
             ('Quetzalcoatl', 2.544270656955212, 0.5704591861565643, 'AMO'),
             ('Boreas', 2.271958775354725, 0.4499332278634067, 'AMO'),
             ('Cuyo', 2.150453953345012, 0.5041719257675564, 'AMO'),
             ('Anteros', 1.430262719980132, 0.2558054402785934, 'AMO'),
             ('Tezcatlipoca', 1.709753263222791, 0.3647772103513082, 'AMO'),
             ('Midas', 1.775954494579457, 0.6503697243919138, 'APO'),
             ('Baboquivari', 2.646202507670927, 0.5295611095751231, 'AMO'),
             ('Anza', 2.26415089613359, 0.5371603112900858, 'AMO'),
             ('Aten', 0.9668828078092987, 0.1827831025175614, 'ATE'),
             ('Bacchus', 1.078135348117527, 0.3495569270441645, 'APO'),
             ('Ra-Shalom', 0.8320425524852308, 0.4364726062545577, 'ATE'),
             ('Adonis', 1.874315684524321, 0.763949321566, 'APO'),
             ('Tantalus', 1.289997492877751, 0.2990853014998932, 'APO'),
             ('Aristaeus', 1.599511990737142, 0.5030618532252225, 'APO'),
             ('Oljato', 2.172056090036035, 0.7125729402616418, 'APO'),
             ('Pele', 2.291471988746353, 0.5115484924883255, 'AMO'),
             ('Hephaistos', 2.159619960333728, 0.8374146846143349, 'APO'),
             ('Orthos', 2.404988778495748, 0.6569133796135244, 'APO'),
             ('Hathor', 0.8442121506103012, 0.4498204013480316, 'ATE'),
             ('Beltrovata', 2.104690977122337, 0.413731105995413, 'AMO'),
             ('Seneca', 2.516402574514213, 0.5708728441169761, 'AMO'),
             ('Krok', 2.152545170235639, 0.4478259793515817, 'AMO'),
             ('Eger', 1.404478323548423, 0.3542971360331806, 'APO'),
             ('Florence', 1.768227407864309, 0.4227761019048867, 'AMO'),
             ('Nefertiti', 1.574493139339916, 0.283902719273878, 'AMO'),
             ('Phaethon', 1.271195939723604, 0.8898716672181355, 'APO'),
             ('Ul', 2.102493486378346, 0.3951143067760007, 'AMO'),
             ('Seleucus', 2.033331705805067, 0.4559159977082651, 'AMO'),
             ('McAuliffe', 1.878722427225527, 0.3691521497610656, 'AMO'),
             ('Syrinx', 2.469752836845105, 0.7441934504192601, 'APO'),
             ('Orpheus', 1.209727780883745, 0.3229034563257626, 'APO'),
             ('Khufu', 0.989473784873371, 0.468479627898914, 'ATE'),
             ('Verenia', 2.093231870619781, 0.4865133359612604, 'AMO'),
             ('"Don Quixote"', 4.221712367193639, 0.7130894892477316, 'AMO'),
             ('Mera', 1.644476057737928, 0.3201425983025733, 'AMO')]

# Each element is (name, semi-major axis (AU), eccentricity, orbit class)
orbit_class = {'AMO':'Amor', 'APO':'Apollo', 'ATE':'Aten'}

# Given this list of asteroid information, let's find all asteroids with semi-major
# axis within 0.2AU of earth, and with eccentricities less than 0.5


print([t[0] for t in Asteroids if (0.8<t[1]<=1.2) and (t[2]<0.5)])

['Cerberus', 'Aten', 'Bacchus', 'Ra-Shalom', 'Hathor', 'Khufu']


In [101]:
# print the list sorted in alphabetical order by asteroid name

names = [t[0] for t in Asteroids if (0.8<t[1]<=1.2) and (t[2]<0.5)]
names.sort()
print(names)
print() 
# sort by name
filtered_asteroids = [t for t in Asteroids if (0.8<t[1]<=1.2) and (t[2]<0.5)]
sorted_by_name = sorted(filtered_asteroids, key = lambda x: x[0])

# sorted by semi-major axis
sorted_by_semimajor = sorted(filtered_asteroids, key = lambda x: x[1])

for t in sorted_by_name:
    print(t)
print()

for t in sorted_by_semimajor:
    print(t)

['Aten', 'Bacchus', 'Cerberus', 'Hathor', 'Khufu', 'Ra-Shalom']

('Aten', 0.9668828078092987, 0.1827831025175614, 'ATE')
('Bacchus', 1.078135348117527, 0.3495569270441645, 'APO')
('Cerberus', 1.079965807367047, 0.4668134997419173, 'APO')
('Hathor', 0.8442121506103012, 0.4498204013480316, 'ATE')
('Khufu', 0.989473784873371, 0.468479627898914, 'ATE')
('Ra-Shalom', 0.8320425524852308, 0.4364726062545577, 'ATE')

('Ra-Shalom', 0.8320425524852308, 0.4364726062545577, 'ATE')
('Hathor', 0.8442121506103012, 0.4498204013480316, 'ATE')
('Aten', 0.9668828078092987, 0.1827831025175614, 'ATE')
('Khufu', 0.989473784873371, 0.468479627898914, 'ATE')
('Bacchus', 1.078135348117527, 0.3495569270441645, 'APO')
('Cerberus', 1.079965807367047, 0.4668134997419173, 'APO')


In [122]:
# replace object name
new_ls = []
for t in sorted_by_name:
    ls = list(t)
    print(ls, ls[3])
    ls[3] = orbit_class[ls[3]]
    new_ls.append(tuple(ls))

new_ls

['Aten', 0.9668828078092987, 0.1827831025175614, 'ATE'] ATE
['Bacchus', 1.078135348117527, 0.3495569270441645, 'APO'] APO
['Cerberus', 1.079965807367047, 0.4668134997419173, 'APO'] APO
['Hathor', 0.8442121506103012, 0.4498204013480316, 'ATE'] ATE
['Khufu', 0.989473784873371, 0.468479627898914, 'ATE'] ATE
['Ra-Shalom', 0.8320425524852308, 0.4364726062545577, 'ATE'] ATE


[('Aten', 0.9668828078092987, 0.1827831025175614, 'Aten'),
 ('Bacchus', 1.078135348117527, 0.3495569270441645, 'Apollo'),
 ('Cerberus', 1.079965807367047, 0.4668134997419173, 'Apollo'),
 ('Hathor', 0.8442121506103012, 0.4498204013480316, 'Aten'),
 ('Khufu', 0.989473784873371, 0.468479627898914, 'Aten'),
 ('Ra-Shalom', 0.8320425524852308, 0.4364726062545577, 'Aten')]

In [129]:

x = np.arange(0,10)
y = 2*x

n = x.shape[0]

x_shifted = x[1:]
y_shifted = y[1:]

print(x)
print(x_shifted)

x_diff = x_shifted - x[:n-1]
y_sum = y_shifted + y[:n-1]
print(y_sum)
y_sum = y_sum.astype(float)
y_sum/=2.
print(y_sum)

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[ 2  6 10 14 18 22 26 30 34]
[ 1.  3.  5.  7.  9. 11. 13. 15. 17.]


In [132]:
def trapz(x,y):

    n = x.shape[0]
    x_shifted = x[1:]
    y_shifted = y[1:]
    
    x_diff = x_shifted - x[:n-1]
    y_sum = y_shifted + y[:n-1]
    y_sum = y_sum.astype(float)
    y_sum/=2.
    
    return np.dot(x_diff, y_sum)

trapz(x,y)

81.0

In [133]:
def trapz(x, y):
    return 0.5*np.sum((x[1:]-x[:-1])*(y[1:]+y[:-1]))

trapz(x,y)

81.0

In [134]:
def trapzf(f, a, b, npts=100):
    x = np.linspace(a, b, npts)
    y = f(x)
    return trapz(x, y)

In [138]:
def f(x):
    return 2*x
trapzf(f, 0,9)

81.0

Write a function count_pairs(N, m) which returns the number of pairs of numbers in the sequence 
 whose sum is divisible by m.

For example, if N = 3 and m = 2, the pairs are

[(0, 1), (0, 2), (1, 2)]
The sum of each pair respectively is [1, 2, 3], and there is a single pair whose sum is divisible by 2, so the result is 1.

What is the result for 
?
What is the result for 
?

In [148]:
def count_pairs(N, m):
    pass

N = 3
m = 2

r = np.arange(3).reshape(3,1)
c = np.arange(3).reshape(1,3)

arr = r+c
#print(np.argwhere(arr%2==0))




def count_pairs_loop(N, m):
    count = 0
    pairs = []
    for i in range(N):
        for j in range(i + 1, N):
            if (i + j) % m == 0:
                count += 1
                pairs.append((i,j))
    return pairs

# Example usage
print(count_pairs_loop(3, 2))

[(0, 2)]


In [147]:
#def count_pairs(N,m):
arr = np.arange(N)
sums = arr[:,None] + arr[None, :]
# avoid duplicate counting
sums_upper = np.triu(sums)
divisible = sums_upper%2 == 0
np.argwhere(divisible)

array([[0, 0],
       [0, 2],
       [1, 0],
       [1, 1],
       [2, 0],
       [2, 1],
       [2, 2]], dtype=int64)

### Set

In [49]:
a = 'heyahow are you'
set_a = set(a)
set_a

{' ', 'a', 'e', 'h', 'o', 'r', 'u', 'w', 'y'}

In [51]:
'a' in set_a

True

In [52]:
a = ['heyahow are you']
set_a = set(a)
set_a

{'heyahow are you'}

In [53]:
'a' in set_a

False

In [149]:
import pandas as pd

In [150]:
df = pd.read_csv("datasets/asteroids5000.csv")
df.head(2)

#a         e          i     H  diameter     BV     UB
0  2.766807  0.075797  10.593981  3.34     952.4  0.713  0.426
1  2.772434  0.231565  34.836257  4.13     545.0  0.635  0.284

In [151]:
df.isna().sum()

#a             0
e              0
i              0
H              0
diameter    3082
BV          4059
UB          4100
dtype: int64

In [152]:
nandf = df[df.isna().any(axis = 1)]
nandf

#a         e          i      H  diameter     BV     UB
32    2.867773  0.336856   1.868784   8.55       NaN  0.848  0.438
63    2.681544  0.126832   1.310186   7.67       NaN  0.734  0.254
72    2.665216  0.044128   2.370454   9.00     44.44    NaN    NaN
126   2.755397  0.065880   8.240407   8.30    122.00    NaN    NaN
139   2.667607  0.213584  11.889643   8.20    131.03    NaN    NaN
...        ...       ...        ...    ...       ...    ...    ...
4995  2.729474  0.123413  12.227612  12.80       NaN    NaN    NaN
4996  2.916651  0.018102   2.952126  12.20       NaN    NaN    NaN
4997  2.684141  0.207573   6.455905  12.70       NaN    NaN    NaN
4998  2.605270  0.124152  11.921943  11.90       NaN    NaN    NaN
4999  3.014279  0.080232  10.372670  12.10       NaN    NaN    NaN

[4233 rows x 7 columns]

In [154]:
notnandf = df[~df.isna().any(axis = 1)]
notnandf

#a         e          i      H  diameter     BV     UB
0     2.766807  0.075797  10.593981   3.34    952.40  0.713  0.426
1     2.772434  0.231565  34.836257   4.13    545.00  0.635  0.284
2     2.670305  0.255287  12.980579   5.33    233.92  0.824  0.433
3     2.361384  0.088502   7.140518   3.20    530.00  0.782  0.492
4     2.574572  0.190872   5.367795   6.85    119.07  0.826  0.411
...        ...       ...        ...    ...       ...    ...    ...
2207  3.994646  0.152564   5.165132  10.18     54.94  0.739  0.246
2237  3.015135  0.078634   9.154577  10.80     26.63  0.806  0.431
2268  3.164119  0.276308   0.469249  10.90     31.60  0.661  0.322
2294  3.204682  0.133434   2.247460  12.09     25.43  0.698  0.312
2639  3.990895  0.119714  13.448531  10.04     57.90  0.724  0.255

[767 rows x 7 columns]

In [155]:
nandf3 = df[df[['BV', 'UB']].isna().any(axis = 1)]
nandf3

#a         e          i      H  diameter  BV  UB
72    2.665216  0.044128   2.370454   9.00     44.44 NaN NaN
126   2.755397  0.065880   8.240407   8.30    122.00 NaN NaN
139   2.667607  0.213584  11.889643   8.20    131.03 NaN NaN
152   3.195781  0.077181  20.974194   7.58    184.93 NaN NaN
155   2.580894  0.195484  12.162221  10.60       NaN NaN NaN
...        ...       ...        ...    ...       ...  ..  ..
4995  2.729474  0.123413  12.227612  12.80       NaN NaN NaN
4996  2.916651  0.018102   2.952126  12.20       NaN NaN NaN
4997  2.684141  0.207573   6.455905  12.70       NaN NaN NaN
4998  2.605270  0.124152  11.921943  11.90       NaN NaN NaN
4999  3.014279  0.080232  10.372670  12.10       NaN NaN NaN

[4100 rows x 7 columns]

In [156]:
nandf3 = df[df[['BV']].isna().any(axis = 1)]
nandf3

#a         e          i      H  diameter  BV  UB
72    2.665216  0.044128   2.370454   9.00     44.44 NaN NaN
126   2.755397  0.065880   8.240407   8.30    122.00 NaN NaN
139   2.667607  0.213584  11.889643   8.20    131.03 NaN NaN
152   3.195781  0.077181  20.974194   7.58    184.93 NaN NaN
155   2.580894  0.195484  12.162221  10.60       NaN NaN NaN
...        ...       ...        ...    ...       ...  ..  ..
4995  2.729474  0.123413  12.227612  12.80       NaN NaN NaN
4996  2.916651  0.018102   2.952126  12.20       NaN NaN NaN
4997  2.684141  0.207573   6.455905  12.70       NaN NaN NaN
4998  2.605270  0.124152  11.921943  11.90       NaN NaN NaN
4999  3.014279  0.080232  10.372670  12.10       NaN NaN NaN

[4059 rows x 7 columns]